development:
  adapter: sqlite3
  database: db/website.db
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/cucumber-tests.db
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  pool: 25
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>