development:
  adapter: sqlite3
  database: db/website.db
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/cucumber-tests.db
  pool: 25
  timeout: 5000
production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRESQL_ADDON_DB'] %>
  username: <%= ENV['POSTGRESQL_ADDON_USER'] %>
  password: <%= ENV['POSTGRESQL_ADDON_PASSWORD'] %>
  pool: 25
  host: <%= ENV['POSTGRESQL_ADDON_HOST'] %>
  port: <%= ENV['POSTGRESQL_ADDON_PORT'] %>