language: node_js
sudo: required
dist: trusty
os:
- linux
node_js:
- 5.0.0
cache: 
  bundler: true
  directories:
    - node_modules
    - .sass-cache
    - ~/travis/.rvm/rubies/ruby-2.3.3
before_install:
- "./core/scripts/travis-install.sh"
- ls ~/
- rvm install 2.3.3
- gem install bundler
install:
- npm install || true
- ./node_modules/.bin/grunt production
before_deploy:
- rm -rf .bundle/
deploy:
  provider: heroku
  condition: "$(uname) == Darwin"
  app: christianjuth
  skip_cleanup: true
  run: rake db:migrate
  on:
    repo: Christianjuth/portfolio
  api_key:
    secure: XW32ibms7DgHnvAVmNVTk3AJ+IJkg6a76lzw/b9qYHo5U97TW9k01lcSNjRr6HxAPzBy4y1AsSPInUJXVBVsy9jFZ5/QCHape9MTRalS2uewYVJWnL/a4skpCQLB6QaeeDhNbMWDG8ssQndSPZosslIXC2km5nPVK/M5o7zyd2yg1sCdWNaY+j+h9xwOA7X3a5dRPhAcWjeKjMq9HAS3BacA0IPXmjW5fYpU8rtoln8xcd6/ACGSTu/ibW9R4OmGXc4dc46NscAOR6SloNfk4qC1iPoHkn091R+0Chnx1AVjBkFs2IgNrA9uzz6fFoLArb67+HIVCHJNd8JXeM7duEBmlAqnApFeuFE/noxagMGRXyhyhb02sfRf1aaGIEWt/40IMvxP5KumYFoNowsIcHI3JXb1JNjNVNXnPB8hYsHPzw0X02CWU7m9w6etRAeYXF4yi9NO0gOzTlWHXA3ATRjKbqlPiwsN1yXQX6616DOLOwKQF0t7N5Qer95UxtbnTr3Kx+glmdsegYGr4S/iri29RJxS8uglu/GWs6Uw6ARJgwl4GkShcCcLOKe+j9xabP2FminEaCWOZ/i0Ilj2AEVfK9U7So/PsmPmkEfa6crNCBdGQRgXY54ArOY4Iob7vs2yRV67Opuxo3Hm+A1ESJguHFfBzp290kYgiMr4+GA=
