source "https://rubygems.org"
ruby "2.4.0"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "rake"
gem "bcrypt"
gem "json"
gem "sinch_sms"
gem "database_cleaner"
gem "recaptcha"
gem "cloudinary"
gem "algoliasearch"
require "rss"

group :development, :test do
  gem "rerun"
  gem "pry"
  gem "tux"
  gem "sqlite3"
  gem "sass"
  gem "thin"
  gem "sinatra-contrib", require: "sinatra/reloader"
end

group :test do
  gem "cucumber"
  gem "capybara", :require => false
  gem "capybara-screenshot", :require => false
  gem "capybara-webkit"
  gem "minitest", require: "minitest/spec"
  gem "codacy-coverage"
  gem "simplecov"
end

group :production do
  gem "pg"
end